# One CLI to format the code tree - https://git.numtide.com/numtide/treefmt

[formatter.stylua]
# Formatter to run
command = "stylua"
# Command-line arguments for the command
options = []
# Glob pattern of files to include
includes = [ "*.lua" ]
# Glob patterns of files to exclude
excludes = []

[formatter.nixfmt-rfc-style]
# Formatter to run
command = "nixfmt"
# Command-line arguments for the command
options = []
# Glob pattern of files to include
includes = [ "*.lua" ]
# Glob patterns of files to exclude
excludes = []
